"""Trains and loads the logistic-regression confidence scorer.

Training data is self-labeled from the synthetic ground truth: every true
(settlement, ledger) pair is a positive example; every other same-bucket
candidate pair is a hard negative. No manual annotation needed.
"""
import os

import joblib
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

from engine.features import FEATURE_ORDER, features_to_vector

MODEL_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "models", "confidence_model.joblib")


def build_training_examples(settlements, ledgers, ground_truth_df, bucket_pairs):
    """bucket_pairs: list of (srow, lrow) candidate pairs already generated by bucketing.

    Returns X (feature matrix), y (labels) using the held-out ground truth only
    to assign labels -- the matching engine itself never reads ground truth.
    """
    from engine.features import compute_features

    true_pairs = set()
    for _, gt in ground_truth_df.iterrows():
        if gt["should_match"] in (True, "True", "true", "1", 1) and gt["invoice_id"]:
            true_pairs.add((gt["settlement_id"], gt["invoice_id"]))

    X, y = [], []
    for srow, lrow in bucket_pairs:
        feats = compute_features(srow, lrow)
        label = 1 if (srow["settlement_id"], lrow["invoice_id"]) in true_pairs else 0
        X.append(features_to_vector(feats))
        y.append(label)
    return np.array(X), np.array(y)


def train_confidence_model(X, y, test_size_frac=0.4):
    """60/20/20 split via two successive splits, stratified where possible."""
    strat = y if len(set(y)) > 1 else None
    X_train, X_rest, y_train, y_rest = train_test_split(
        X, y, test_size=test_size_frac, random_state=42, stratify=strat)
    strat_rest = y_rest if len(set(y_rest)) > 1 else None
    X_val, X_test, y_val, y_test = train_test_split(
        X_rest, y_rest, test_size=0.5, random_state=42, stratify=strat_rest)

    model = LogisticRegression(max_iter=1000, class_weight="balanced")
    model.fit(X_train, y_train)

    report = {
        "n_train": len(X_train), "n_val": len(X_val), "n_test": len(X_test),
        "train_acc": model.score(X_train, y_train),
        "val_acc": model.score(X_val, y_val) if len(X_val) else None,
        "test_acc": model.score(X_test, y_test) if len(X_test) else None,
    }
    return model, report, (X_test, y_test)


def save_model(model):
    os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)
    joblib.dump(model, MODEL_PATH)


def load_model():
    if not os.path.exists(MODEL_PATH):
        return None
    return joblib.load(MODEL_PATH)


def predict_confidence(model, features: dict) -> float:
    """Fail-safe: no model loaded -> confidence 0.0, which always routes away from auto-match."""
    if model is None:
        return 0.0
    vec = np.array([features_to_vector(features)])
    return float(model.predict_proba(vec)[0][1])
